### PR TITLE
wr-106: Article page doesn't match the design

### PR DESCRIPTION
**Pull request by AnastasiaR2**
Created container and styles for article component to place the author section on the right side form the article.

image

### CODE REVIEW

**Review by andanf-e — CHANGES_REQUESTED** [review]
image
From the screenshot provided it looks like articles page still does not have inline padding as on the design + I believe that inline padding should be the same for all pages (except Sign In\Sign Up with it's own layout)
Also top padding may also be added for all pages

**Comment by AnastasiaR2** [comment]
It is required to create paddings separately on every page, or some general styles for all pages?

**Comment by andanf-e** [comment]
> It is required to create paddings separately on every page, or some general styles for all pages?

General, mb create some Layout component, or smth like that and wrap pages that need to have it

**Review by andanf-e — APPROVED** [review]
But update screenshot please

**Review by NazarKovtun1 — APPROVED** [review]

**Pull request merged**
